function out1 = explicitSkeletalDynamics(Fx,Fy,I1,I2,Telbow,Tshoulder,TEXT,dq1,dq2,l1,l2,lc1,lc2,m1,m2,q1,q2)
%EXPLICITSKELETALDYNAMICS
%    OUT1 = EXPLICITSKELETALDYNAMICS(FX,FY,I1,I2,TELBOW,TSHOULDER,DQ1,DQ2,L1,L2,LC1,LC2,M1,M2,Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    09-Nov-2021 22:14:38

t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
t6 = q1+q2;
t7 = dq1.*2.0;
t8 = dq1.^2;
t9 = l1.^2;
t10 = lc1.^2;
t11 = lc2.^2;
t12 = m2.^2;
t13 = I1.*I2;
t14 = t3.^2;
t15 = cos(t6);
t16 = sin(t6);
t17 = dq2+t7;
t18 = m2.*t11;
t19 = Fy.*l1.*t2;
t20 = Fx.*l1.*t4;
t21 = l1.*lc2.*m2.*t3;
t22 = I2.*m2.*t9;
t23 = I2.*m1.*t10;
t28 = l1.*lc2.*m2.*t5.*t8;
t31 = t9.*t11.*t12;
t24 = I1.*t18;
t25 = Fy.*l2.*t15;
t26 = Fx.*l2.*t16;
t27 = -t20;
t30 = m1.*t10.*t18;
t32 = -t28;
t33 = dq2.*l1.*lc2.*m2.*t5.*t17;
t34 = I2+t18+t21;
t35 = t14.*t31;
t29 = -t26;
t36 = -t35;
t37 = Telbow+TEXT(2)+t25+t29+t32;
t38 = Tshoulder+TEXT(1)+t19+t25+t27+t29+t33;
t39 = t13+t22+t23+t24+t30+t31+t36;
t40 = 1.0./t39;
out1 = [t38.*t40.*(I2+t18)-t34.*t37.*t40;t37.*t40.*(I1+t21+t34+m1.*t10+m2.*t9)-t34.*t38.*t40];
